// react-client/src/components/movie-details.component.js
import React, {useState, useEffect, useCallback} from 'react';
import {useParams} from 'react-router-dom';
import MovieService from '../services/movie.service';
import './css/movie-details.component.css';
import ScreenshotDialog from "./screenshot-dialog.component";

const MovieDetails = () => {
    const [movie, setMovie] = useState(null);
    const [hoveredDirector, setHoveredDirector] = useState(null);
    const [hoveredActor, setHoveredActor] = useState(null);
    const [selectedScreenshot, setSelectedScreenshot] = useState(null);
    const {id} = useParams();

    const retrieveMovie = useCallback(() => {
        MovieService.getMovieById(id)
            .then(response => {
                setMovie(response.data);
                console.log(response.data);
            })
            .catch(e => {
                console.error(e);
            });
    }, [id]);

    useEffect(() => {
        retrieveMovie();
    }, [retrieveMovie]);

    if (!movie) {
        return <div>Loading...</div>;
    }

    return (
        <div className="container mt-3">
            <div className="row">
                <div className="col-md-6">
                    <img className="img-fluid" src={movie.poster} alt="Movie poster"/>
                </div>
                <div className="col-md-6">
                    <h2>{movie.ruTitle}</h2>
                    <p>{movie.description}</p>
                    <p><strong>Год производства:</strong> {movie.releaseYear}</p>
                    <p><strong>Продолжительность:</strong> {movie.length} минут</p>
                    <p><strong>Жанры:</strong> {movie.genres.map(genre => genre.name).join(', ')}</p>
                    <p><strong>Режиссеры:</strong> {movie.directors.map((director, index) => (
                        <span
                            key={index}
                            onMouseEnter={() => setHoveredDirector(director)}
                            onMouseLeave={() => setHoveredDirector(null)}
                            className="director"
                        >
              {director.ruName}
                            {hoveredDirector === director &&
                                <img className="hover-image" src={director.photo} alt="Director"/>}
            </span>
                    )).reduce((prev, curr, index) => [prev, ', ', curr])}</p>
                    <p><strong>Актеры:</strong> {movie.actors.map((actor, index) => (
                        <span
                            key={index}
                            onMouseEnter={() => setHoveredActor(actor)}
                            onMouseLeave={() => setHoveredActor(null)}
                            className="actor"
                        >
              {actor.ruName}
                            {hoveredActor === actor && <img className="hover-image" src={actor.photo} alt="Actor"/>}
            </span>
                    )).reduce((prev, curr, index) => [prev, ', ', curr])}</p>
                    <div className="screenshot-container">
                        {movie.movieScreenshots.map((screenshot, index) => (
                            <img key={index} src={screenshot.url} alt="Movie screenshot"
                                 onClick={() => setSelectedScreenshot(screenshot.url)}/>
                        ))}
                    </div>
                </div>
            </div>
            {movie.album && (
                <div className="album-container">
                    <img src={movie.album.cover} alt="Album cover" className="w-48 h-auto"/>
                    <div className="ml-8">
                        <h2 className="text-2xl font-bold">{movie.album.name}</h2>
                        <a href={movie.album.spotifyUrl} target="_blank" rel="noreferrer" className="spotify-button">Open
                            in Spotify</a>
                    </div>
                </div>
            )}
            {movie.album && movie.album.tracks.map((track, index) => (
                <div key={index} className="track-container">
                    <p>{track.name}</p>
                    <audio controls style={{width: '500px'}}>
                        <source src={track.previewUrl} type="audio/mpeg"/>
                        Your browser does not support the audio element.
                    </audio>
                </div>
            ))}
            <ScreenshotDialog isOpen={!!selectedScreenshot} onRequestClose={() => setSelectedScreenshot(null)}
                              screenshotUrl={selectedScreenshot}/>
        </div>
    );
};

export default MovieDetails;

// angular-client/src/app/components/movie/movie-details/movie-details.component.ts
import {Component, OnInit} from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import {MovieService} from "../../../services/movie/movie.service";
import {Movie} from "../../../models/movie/movie.model";
import {MatDialog} from '@angular/material/dialog';
import {ScreenshotDialogComponent} from '../screenshot-dialog/screenshot-dialog.component';

@Component({
  selector: 'app-movie-details',
  templateUrl: './movie-details.component.html',
  styleUrls: ['./movie-details.component.css']
})
export class MovieDetailsComponent implements OnInit {
  movie?: Movie;
  id: number;
  hover: boolean[];
  hoverDirectors: boolean[];
  displayedScreenshots: any[];
  screenshotIndex: number;

  constructor(private movieService: MovieService, private route: ActivatedRoute, public dialog: MatDialog) { // Добавлен MatDialog в конструктор
    this.id = 0;
    this.hover = [];
    this.hoverDirectors = [];
    this.displayedScreenshots = [];
    this.screenshotIndex = 0;
  }

  ngOnInit(): void {
    this.id = this.route.snapshot.params['id'];
    this.movieService.getMovieById(this.id).subscribe(data => {
      this.movie = data;
      console.log(data);
      this.updateDisplayedScreenshots();
    });
  }

  updateDisplayedScreenshots(): void {
    if (this.movie && this.movie.movieScreenshots) {
      this.displayedScreenshots = this.movie.movieScreenshots.slice(this.screenshotIndex, this.screenshotIndex + 6);
    }
  }

  scrollLeft(): void {
    if (this.screenshotIndex > 0) {
      this.screenshotIndex -= 3;
      this.updateDisplayedScreenshots();
    }
  }

  scrollRight(): void {
    if (this.movie && this.movie.movieScreenshots && this.screenshotIndex < this.movie.movieScreenshots.length - 6) {
      this.screenshotIndex += 3;
      this.updateDisplayedScreenshots();
    }
  }

  openDialog(screenshot: any): void {
    this.dialog.open(ScreenshotDialogComponent, {
      data: {url: screenshot.url}
    });
  }
}

<div class="flex flex-col items-center">
  <div class="flex flex-row justify-between my-8">
    <div class="w-1/3">
      <img [src]="movie?.poster" [alt]="movie?.enTitle" class="w-full h-auto">
    </div>
    <div class="w-2/3 ml-8">
      <h2 class="text-3xl font-bold">{{ movie?.ruTitle }}</h2>
      <p class="mt-2 text-xl">{{ movie?.enTitle }}</p>
      <p class="mt-4 text-lg">{{ movie?.description }}</p>
      <br>
      <div *ngFor="let genre of movie?.genres"
           class="inline-block bg-custom-green rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">{{ genre.name }}
      </div>

      <br>
      <p class="mt-2"><strong>Год производства:</strong> {{ movie?.releaseYear }}</p>
      <p class="mt-2"><strong>Продолжительность:</strong> {{ movie?.length }} минут</p>
      <br>

      <p class="mt-2"><strong>Режиссер:</strong>
        <ng-container *ngFor="let director of movie?.directors; let i = index; let isLast = last">
          <span class="relative director" (mouseover)="hoverDirectors[i] = true" (mouseout)="hoverDirectors[i] = false">
            {{ director.ruName }}
            <div class="absolute bg-white p-2 border border-gray-300 rounded-lg shadow-lg director-card z-50"
                 [style.left.px]="0" [style.top.px]="20" *ngIf="hoverDirectors[i]">
              <h4>{{ director.enName }}</h4>
              <img [src]="director.photo" alt="Director photo" class="w-48 h-auto object-scale-down rounded-lg">
            </div>
          </span>
          <ng-container *ngIf="!isLast">,</ng-container>
        </ng-container>
      </p>

      <p class="mt-2"><strong>Актерский состав:</strong>
        <ng-container *ngFor="let actor of movie?.actors; let i = index; let isLast = last">
          <span class="relative actor" (mouseover)="hover[i] = true" (mouseout)="hover[i] = false">
            {{ actor.ruName }}
            <div class="absolute bg-white p-2 border border-gray-300 rounded-lg shadow-lg actor-card z-50"
                 [style.left.px]="0" [style.top.px]="20" *ngIf="hover[i]">
              <h4>{{ actor.enName }}</h4>
              <img [src]="actor.photo" alt="Actor photo" class="w-48 h-auto object-scale-down rounded-lg">
            </div>
          </span>
          <ng-container *ngIf="!isLast">,</ng-container>
        </ng-container>
      </p>

      <div *ngIf="displayedScreenshots.length > 0">
        <br>
        <p class="mt-2"><strong>Кадры из фильма</strong></p>
        <div class="flex items-center mt-8">
          <button
            class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded"
            (click)="scrollLeft()">←
          </button>

          <div class="overflow-x-auto ml-4">
            <div *ngFor="let screenshot of displayedScreenshots" class="mr-4 screenshot-container">
              <img [src]="screenshot.url" class="w-48 h-auto" alt="Movie screenshot" (click)="openDialog(screenshot)">
            </div>
          </div>

          <button
            class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded ml-4"
            (click)="scrollRight()">→
          </button>
        </div>
      </div>
    </div>
  </div>
  <div *ngIf="movie?.album" class="album-container flex items-center">
    <img [src]="movie?.album?.cover" [alt]="movie?.album?.name" class="w-48 h-auto">
    <div class="ml-8">
      <h2 class="text-2xl font-bold bg-">{{ movie?.album?.name }}</h2>
      <a [href]="movie?.album?.spotifyUrl" target="_blank" class="spotify-button">Open in Spotify</a>
    </div>
  </div>
  <div *ngFor="let track of movie?.album?.tracks" class="track-container">
    <p>{{ track.name }}</p>
    <audio controls style="width: 500px;">
      <source [src]="track.previewUrl" type="audio/mpeg">
      Your browser does not support the audio element.
    </audio>
  </div>
</div>
