// react-client/src/components/movie-list.component.js
import React, {useState, useEffect} from 'react';
import { Link } from 'react-router-dom';
import MovieService from '../services/movie.service';
import './css/movie-list.component.css';

const MovieList = () => {
    const [movies, setMovies] = useState([]);
    const [searchTerm, setSearchTerm] = useState('');
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        retrieveMovies();
    }, []);

    const retrieveMovies = () => {
        MovieService.getAllMoviesDto()
            .then(response => {
                setMovies(response.data);
                console.log(response.data);
                setIsLoading(false);
            })
            .catch(e => {
                console.error(e);
                setIsLoading(false);
            });
    };

    if (isLoading) {
        return <div>Loading...</div>;
    }
    const handleSearchTermChange = event => {
        setSearchTerm(event.target.value);
    };

    const filteredMovies = movies.filter(movie =>
        movie.ruTitle.toLowerCase().includes(searchTerm.toLowerCase())
    );

    return (
        <div className="container mt-3">
            <input
                value={searchTerm}
                onChange={handleSearchTermChange}
                placeholder="Поиск по названию фильма"
                className="form-control mb-3"
            />
            <div className="grid">
                {filteredMovies.map((movie, index) => (
                    <div className="card" key={index}>
                        <Link to={`/movies/${movie.id}`}>
                            <img className="card-img-top" src={movie.poster} alt="Movie poster"/>
                            <div className="card-body">
                                <h5 className="card-title">{movie.ruTitle}</h5>
                                <p className="card-text">
                                    <small className="text-muted">{movie.releaseYear}</small>
                                </p>
                                <p className="card-text">{movie.length} минут</p>
                                <p className="card-text">Жанры: {movie.genres.join(', ')}</p>
                            </div>
                        </Link>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default MovieList;

// angular-client/src/app/components/movie/movie-list/movie-list.component.ts
// movie-list.component.ts
import {Component, OnInit} from '@angular/core';
import {MovieService} from "../../../services/movie/movie.service";
import {MovieDto} from "../../../models/movie/movie-dto.model";

@Component({
  selector: 'app-movie-list',
  templateUrl: './movie-list.component.html',
  styleUrls: ['./movie-list.component.css']
})
export class MovieListComponent implements OnInit {
  movies: MovieDto[] = [];
  currentMovie: {} = <MovieDto>{};
  currentIndex = -1;
  title = '';
  filteredMovies: MovieDto[] = [];
  private _searchTerm = '';

  get searchTerm(): string {
    return this._searchTerm;
  }

  set searchTerm(value: string) {
    this._searchTerm = value;
    this.filteredMovies = this.filterMovies(this._searchTerm);
  }

  constructor(private movieService: MovieService) {
  }

  ngOnInit(): void {
    this.retrieveMovies();
  }

  retrieveMovies(): void {
    this.movieService.getAllMoviesDto().subscribe({
      next: (data) => {
        this.movies = data;
        this.filteredMovies = [...this.movies]; // Изначально отображаем все фильмы
        console.log('Movies:', this.movies);
      },
      error: (e) => console.error(e)
    });
  }

  refreshList(): void {
    this.retrieveMovies();
    this.currentMovie = {};
    this.currentIndex = -1;
  }

  setActiveMovie(movie: MovieDto, index: number): void {
    this.currentMovie = movie;
    this.currentIndex = index;
  }

  filterMovies(searchTerm: string) {
    if(!searchTerm) {
      return this.movies;
    }

    return this.movies.filter(movie => movie.ruTitle.toLowerCase().includes(searchTerm.toLowerCase()));
  }
}

<div class="container mt-3">
  <input [(ngModel)]="searchTerm" placeholder="Поиск по названию фильма" class="form-control mb-3">
  <div class="grid">
    <div class="card" *ngFor="let movie of filteredMovies">
      <a [routerLink]="['/movies', movie.id]">
        <img class="card-img" [src]="movie.poster" alt="Movie poster">
        <div class="card-body">
          <h5 class="card-title">{{movie.ruTitle}}</h5>
          <p class="card-text"><small class="text-muted">{{movie.releaseYear}}</small></p>
          <p class="card-text">{{movie.length}} минут</p>
          <p class="card-text">Жанры: {{movie.genres.join(', ')}}</p>
        </div>
      </a>
    </div>
  </div>
</div>
